### ISSUE TITLE
couldn't get dscore submodule

### ISSUE THREAD

**Issue by Iridescent1318** [BUTSpeechFIT/VBx#1]
Hi,
I am following the steps in README. When initializing the submodule `dscore`,  the git submodule commands return nothing in the terminal (like this)
```
(vbx) liaozty20@a11:~/VBx$ git submodule init
(vbx) liaozty20@a11:~/VBx$ git submodule update
(vbx) liaozty20@a11:~/VBx$ 
```
and the `dscore` directory is not created. The provided example works except that it can't find `dscore/score.py`. I try to see config in `.git` but I can't find anything about the submodule. 
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/BUTSpeechFIT/VBx.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Comment by Jamiroquai88** [comment]
Hi, thank you for using the software. Looks like we forgot to add the `.gitmodules` file.
@fnlandini could you please create a file named `.gitmodules` with the following content?
```
[submodule "dscore"]
	path = dscore
	url = https://github.com/nryant/dscore
```
Thanks. @fnlandini could you please change settings so I can create and push into this branch? I am getting an error:
```bash
git push --set-upstream origin dscore_fix
```
```
remote: Permission to BUTSpeechFIT/VBx.git denied to Jamiroquai88.
fatal: unable to access 'https://github.com/BUTSpeechFIT/VBx.git/': The requested URL returned error: 403
```

**Comment by fnlandini** [comment]
Hi,
Thank you @Iridescent1318 for pointing it out. @Jamiroquai88 proposal is in place now. Let us know if you find any other problems .

**Comment by Iridescent1318** [comment]
I pulled the new version just now. The init and update commands seemed still not working, so I manually added the submodule
```
git submodule add https://github.com/nryant/dscore.git
```
Although I have no idea why init and update commands didn't give any response, manually adding the submodule works now. 
Thanks for your help!
