### ISSUE TITLE
Overlapping speech

### ISSUE THREAD

**Issue by YannisTevissen** [BUTSpeechFIT/VBx#12]
Hello,

What about overlapping segments with two (or more) people speaking at the same time ?
Is it handled by this solution (it seems it is not but I may have misunderstood something) ? 
If not, do you have ideas on how to tackle this issue ?

Regards,

Yannis

**Comment by fnlandini** [comment]
Hello Yannis,
This solution does not handle overlapped speech as it is. It only gives you one speaker in any speech segment. What we usually do is to use an overlap detector and post-process the output as we did recently here https://arxiv.org/pdf/2010.11718.pdf
Modifying this recipe to handle overlap might be quite some work and we have not succeeded with that yet.

Regards,
Federico

**Comment by YannisTevissen** [comment]
Hello Federico, 
Thanks a lot for your answer. It is very clear and useful. I am currently starting a PhD about diarization in the wild, we should get in touch, I would be very interested in discussing these subjects with you.

Thanks again,
Regards,
Yannis

**Comment by fnlandini** [comment]
Sure, feel free to contact me on my email account.
Federico
