### ISSUE TITLE
Inconsistency between the run_example.sh and vbhmm.py

### ISSUE THREAD

**Issue by wsstriving** [BUTSpeechFIT/VBx#13]
Hi, Fede,
       Hope you are doing well, I tried to run your scripts for voxconverse but didn't make it, the main problem is 
       
```
          python VBx/vbhmm.py --init AHC+VB \
          --out-rttm-dir exp \
          --xvec-ark-file exp/${filename}.ark \   
          --segments-file exp/${filename}.seg \  
          --xvec-transform VBx/models/ResNet101_16kHz/transform.h5 \   # this arg is depreceted in vbhmm.py
          --plda-file VBx/models/ResNet101_16kHz/plda \
          --threshold -0.015 \
          --lda-dim 128 \
          --Fa 0.3 \
          --Fb 17 \
          --loopP 0.99, 

          --xvec-mean # this is required in vbhmm.py but not provided in the shell script, 
                     # also xvec-mean didn't apear in the directory of VBx/models/ResNet101_16kHz
```

It would be great if you can fix this!
Best,
Shuai

**Comment by fnlandini** [comment]
Hi Shuai!
There is actually a small difference between the recipe of VoxConverse and the master. VoxConverse's uses ResNet152 and for that one we have the backend in https://github.com/BUTSpeechFIT/VBx/tree/v1.1_VoxConverse2020/VBx/models/ResNet152_16kHz so there are files _transform.mat_ and _mean_ while for master there is a single _transform.h5_ which contains both. I preferred to release the recipe sooner than to put everything in a single h5 file so it was in my to-do list. 
I will hopefully find time to do it during this week. If it is urgent, in the meantime, you can probably figure out how to use the single transform.h5 from ResNet101 following the code in master.

Best,
Fede

**Comment by wsstriving** [comment]
Hi Fede,
       Thanks, I figured out how to run it following your instructions, the results are exactly the same with the README.
Best,
Shuai
