### ISSUE TITLE
where is the 'dscore/score.py ' in the 'run_example'

### ISSUE THREAD

**Issue by zrtlemontree** [BUTSpeechFIT/VBx#3]
Dear author:
        Thanks for your program, but I don't see the script named 'dscore/score.py ' in the program. Could you give some guidelines for me ?

**Comment by Jamiroquai88** [comment]
Hi, `dscore` refers to https://github.com/nryant/dscore
It should get initialized as a submodule, did you run
```bash
git submodule init
git submodule update
```

**Comment by zrtlemontree** [comment]
Thank your very much, I will try your suggestion.

**Comment by zrtlemontree** [comment]
Thank you for your suggestion. I have successfully run the program now.
