### ISSUE TITLE
AMI beamformed wav

### ISSUE THREAD

**Issue by DTDwind** [BUTSpeechFIT/VBx#30]
Hello~

Your project is so great.
Now, I wanna to try the beamform experiment.
Is your AMI_beamformed based on [Kaldi s5b ](https://github.com/kaldi-asr/kaldi/tree/master/egs/ami/s5b)'s  `--mic mdm8`?

Thank you.

**Comment by fnlandini** [comment]
Hello,
Thank you for the kind words. I am not sure what exactly Kaldi runs. Alike the Kaldi recipe, we used BeamformIt from Xavier Anguera. The AMI configuration parameters are here: https://github.com/xanguera/BeamformIt/blob/master/cfg-files/ami.cfg
Maybe Kaldi uses the same parameters, I did not verify if the parameters they use are the same.

**Comment by DTDwind** [comment]
Thank you for your response. I have confirmed that Kaldi uses the same parameters. https://github.com/kaldi-asr/kaldi/blob/master/egs/ami/s5/conf/ami_beamformit.cfg
But their manual annotations uses v1.6.1, so we maybe need to edit that.
Thanks.
