### ISSUE TITLE
plda and transform.h5

### ISSUE THREAD

**Issue by cathyeee77** [BUTSpeechFIT/VBx#32]
Hello,

I would like to reproduce the result of this work. May I know how you created the plda file and transform.h5 file? I saw a comment in resnet.py showing 'For Pre-activation ResNet, see 'preact_resnet.py'.'. Could you please also share that file as well? 

Thanks a lot!

Kind Regards

**Comment by fnlandini** [comment]
Hello,
Sorry for the delay. The computation of plda and transform.h5 files are defined here: https://github.com/phonexiaresearch/VBx-training-recipe/blob/b699b5f1969e08faa7c0869d506b324613ef5c20/run.sh#L174
We point to this other repository which trains the x-vector extractor and backend files in our README but I agree that it is a bit hidden.

Regards,
Federico

**Comment by cathyeee77** [comment]
Thanks a lot! Great work:)
