### ISSUE TITLE
Is it possible to run clustering algorithm on GPU?

### ISSUE THREAD

**Issue by Sarah-Xing** [BUTSpeechFIT/VBx#34]
I used this toolkit on some long audio files. The clustering stage takes long time, like a couple of hours for a 1.5 hour audio (full of speech). Is this normal? Is it possible to run the clustering algorithm on GPU? Thanks!

**Comment by fnlandini** [comment]
Hello,
We do not have a clustering implementation that would take advantage of a GPU. However, the main bottleneck when processing long recordings is at the AHC step used for initialization. This can be avoided by using another initialization. We have added recently another option to the code but it seems it is a bit hidden so I've added a paragraph in the [Usage](https://github.com/BUTSpeechFIT/VBx/blob/master/README.md#usage) section about this topic.
Let me know if this works for you.

**Comment by videodanchik** [comment]
Hi, @SpeechGirl I have also found the [under-the-hood VBx AHC implementation](https://github.com/BUTSpeechFIT/VBx/blob/master/VBx/diarization_lib.py) extremely slow. With this, I would recommend using `sklearn.cluster.AgglomerativeClustering` with `affinity='precomputed'`, but if you want a fast solution, I would suggest you use `fastcluster` (https://pypi.org/project/fastcluster/) which is an efficient AHC implementation written in C++ and wrapped in python (some benchmarks can be found [here](https://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html)). But there is a trick to make it work, you should replace the following line:
`labels1st = AHC(scr_mx, thr + args.threshold)`
with
```
scr_mx = scipy.spatial.distance.squareform(scr_mx)
lin_mat = fastcluster.linkage(scr_mx, method='average', preserve_input='False')
del scr_mx

# fix the issue with scipy.cluster.hierarchy.fcluster when it fails if negative distances appear in
# linkage matrix. This doesn't affect the speaker labels output as the relative distance between clusters in
# linkage matrix is left unchanged
lin_mat[:, 2] += abs(lin_mat[:, 2].min())
labels1st = scipy.cluster.hierarchy.fcluster(lin_mat, thr + args.threshold) - 1
```

**Comment by fnlandini** [comment]
Thanks @videodanchik for your suggestion! I will keep it in mind when I check your PR (I still haven't had time to go through it :/)

**Comment by Jamiroquai88** [comment]
@videodanchik were you able to obtain the exactly same result? I wrote a simple test, something like:
```python
def old(scr_mx, thr):
    return list(AHC(scr_mx, thr))


def new(scr_mx, thr):
    scr_mx = squareform(scr_mx)
    lin_mat = fastcluster.linkage(scr_mx, method='average', preserve_input='False')
    del scr_mx
    lin_mat[:, 2] += abs(lin_mat[:, 2].min())
    return list(fcluster(lin_mat, thr) - 1)


class MyTestCase(unittest.TestCase):
    def test_speedup(self):
        for _ in range(10):
            a = np.random.rand(10, 10)
            np.fill_diagonal(a, 0)
            a = np.tril(a) + np.tril(a, -1).T
            thr = twoGMMcalib_lin(a.ravel(), var_eps=1e-6)
            a_old = copy.deepcopy(a)
            a_new = copy.deepcopy(a)

            start = time.time()
            old_labels = old(a_old, thr)
            logging.info(f'old() time: {time.time() - start}')
            print(old_labels)

            start = time.time()
            new_labels = new(a_new, thr)
            logging.info(f'new() time: {time.time() - start}')
            print(new_labels)

            self.assertListEqual(old_labels, new_labels)
            
```
and they do not match at all :/

**Comment by Sarah-Xing** [comment]
> Hello,
> We do not have a clustering implementation that would take advantage of a GPU. However, the main bottleneck when processing long recordings is at the AHC step used for initialization. This can be avoided by using another initialization. We have added recently another option to the code but it seems it is a bit hidden so I've added a paragraph in the [Usage](https://github.com/BUTSpeechFIT/VBx/blob/master/README.md#usage) section about this topic.
> Let me know if this works for you.

Thanks for the suggestion. I have tested the random initialization on VoxConverse dev set, DER increased from 4.41% to 8.92% compared to the AHC initialization. Is this performance dropping normal?

**Comment by Sarah-Xing** [comment]
> Hi, @SpeechGirl I have also found the [under-the-hood VBx AHC implementation](https://github.com/BUTSpeechFIT/VBx/blob/master/VBx/diarization_lib.py) extremely slow. With this, I would recommend using `sklearn.cluster.AgglomerativeClustering` with `affinity='precomputed'`, but if you want a fast solution, I would suggest you use `fastcluster` (https://pypi.org/project/fastcluster/) which is an efficient AHC implementation written in C++ and wrapped in python (some benchmarks can be found [here](https://hdbscan.readthedocs.io/en/latest/performance_and_scalability.html)). But there is a trick to make it work, you should replace the following line:
> `labels1st = AHC(scr_mx, thr + args.threshold)`
> with
> 
> ```
> scr_mx = scipy.spatial.distance.squareform(scr_mx)
> lin_mat = fastcluster.linkage(scr_mx, method='average', preserve_input='False')
> del scr_mx
> 
> # fix the issue with scipy.cluster.hierarchy.fcluster when it fails if negative distances appear in
> # linkage matrix. This doesn't affect the speaker labels output as the relative distance between clusters in
> # linkage matrix is left unchanged
> lin_mat[:, 2] += abs(lin_mat[:, 2].min())
> labels1st = scipy.cluster.hierarchy.fcluster(lin_mat, thr + args.threshold) - 1
> ```

Thanks for the suggestion.  I will take a close look.

**Comment by fnlandini** [comment]
> > Hello,
> > We do not have a clustering implementation that would take advantage of a GPU. However, the main bottleneck when processing long recordings is at the AHC step used for initialization. This can be avoided by using another initialization. We have added recently another option to the code but it seems it is a bit hidden so I've added a paragraph in the [Usage](https://github.com/BUTSpeechFIT/VBx/blob/master/README.md#usage) section about this topic.
> > Let me know if this works for you.
> 
> Thanks for the suggestion. I have tested the random initialization on VoxConverse dev set, DER increased from 4.41% to 8.92% compared to the AHC initialization. Is this performance dropping normal?

Hi @SpeechGirl,
If you only ran one random initialization, it is possible for the performance to degrade that much. Since running only the VB inference takes a short time, it is possible to run with different random initializations and then take the one with best ELBO. The code already takes care of this if you specify for example "random_10". I have not tried this initialization specifically with VoxConverse but with DIHARD it would make sense to run 10 initializations. Using 100 would only give a small gain and take too long but 5 or 10 runs in a reasonable time and reaches reasonable performance.

**Comment by videodanchik** [comment]
Hi @Jamiroquai88, you are right, my mistake, I forgot a couple of things: 
1) You need to pass `-scr_mx` instead of `scr_mx` to `scipy.spatial.distance.squareform` (you are doing it on the fly in your `AHC` method explicitly, I moved this sign flip to `PLDA_scoring_in_LDA_space` and forgot to mention).
2) `thr` should also be flipped and adjusted accordingly and `criterion='distance'` should be applied in `fcluster`.
3) Your test is a bit incorrect as it demands the exact equality of the output lists while we need only one-to-one correspondence (the test should pass if, for example, we got something like this: `old_labels = [0, 0, 0, 1, 1]`, `new_labels = [1, 1, 1, 0, 0]`).
4) You won't see much speed up with such small (10 by 10) matrices that correspond to some conversations with only 10 x-vector steps. In reality, the step mentioned in the paper is equal to 0.2 seconds, so having 200 - 400 seconds of speech we will end up with 1000 - 2000 segments that will represent a square matrix of PLDA scores. Really noticeable differences start to appear when the number of segments is equal to 100 at least. Here is what I got with my 16 CPU machine.

```
import timeit
import numpy as np

small = np.random.rand(10, 10)
medium = np.random.rand(100, 100)
big = np.random.rand(1000, 1000)

for input_scr in [small, medium, big]:
    np.fill_diagonal(input_scr, 0)
    input_scr = np.tril(input_scr) + np.tril(input_scr, -1).T
    thr = twoGMMcalib_lin(input_scr.ravel())[0]
    
    input_scr_old = copy.deepcopy(input_scr)
    input_scr_new = copy.deepcopy(input_scr)
    
    time_old = np.mean(timeit.repeat(stmt=lambda: old(input_scr_old, thr), repeat=1000, number=1))
    time_new = np.mean(timeit.repeat(stmt=lambda: new(input_scr_new, thr), repeat=1000, number=1))
    
    print(f'Old time: {round(time_old, 5)}; New time: {round(time_new, 5)}')
    
>>> Old time: 0.00015; New time: 0.0001
>>> Old time: 0.00297; New time: 0.00036
>>> Old time: 1.12131; New time: 0.00927
```

I expect these results will be consistent on the arbitrary machine. As you can see for 1000 by 1000 matrix it is already more than 100 times faster.

And here additionally the working version of your proposed test:

```
def old(scr_mx, thr):
    return list(AHC(scr_mx, thr))


def new(scr_mx, thr):
    scr_mx = squareform(-scr_mx)
    lin_mat = fastcluster.linkage(scr_mx, method='average', preserve_input='False')
    del scr_mx
    adjust = abs(lin_mat[:, 2].min())
    lin_mat[:, 2] += adjust
    return list(fcluster(lin_mat, -thr+adjust, criterion='distance') - 1)

class MyTestCase(unittest.TestCase):
    def test_speedup(self):
        for _ in range(10):
            a = np.random.rand(10, 10)
            np.fill_diagonal(a, 0)
            a = np.tril(a) + np.tril(a, -1).T
            thr = twoGMMcalib_lin(a.ravel(), var_eps=1e-6)
            a_old = copy.deepcopy(a)
            a_new = copy.deepcopy(a)

            start = time.time()
            old_labels = old(a_old, thr)
            logging.info(f'old() time: {time.time() - start}')
            print(old_labels)

            start = time.time()
            new_labels = new(a_new, thr)
            logging.info(f'new() time: {time.time() - start}')
            print(new_labels)

            old_labels_dict, new_labels_dict = {}, {}
            for idx, (old_l, new_l) in enumerate(zip(old_labels, new_labels)):
                if old_l in old_labels_dict:
                    old_labels_dict[old_l].append(idx)
                else:
                    old_labels_dict[old_l] = [idx]
                    
                if new_l in new_labels_dict:
                    new_labels_dict[new_l].append(idx)
                else:
                    new_labels_dict[new_l] = [idx]

            self.assertListEqual(list(old_labels_dict.values()), list(new_labels_dict.values()))
            self.assertSetEqual(set(old_labels_dict), set(new_labels_dict))
```

@fnlandini I haven't added this to my PR yet, but can do it if you and @Jamiroquai88  approve.

**Comment by Jamiroquai88** [comment]
@videodanchik many thanks
@fnlandini looks ok to me, it passed my "artificial" tests and it is much faster

**Comment by fnlandini** [comment]
Hi @SpeechGirl 
We have just added to the master branch the modifications proposed by @videodanchik 
If you have time, it would be nice if you can let us know if this faster clustering is enough for the long files you were working with. I have tried it out only on shorter ones but I am curious about the 1.5 hours case you mentioned.
Thanks,
Federico

**Comment by hxing093020** [comment]
> Hi @SpeechGirl
> We have just added to the master branch the modifications proposed by @videodanchik
> If you have time, it would be nice if you can let us know if this faster clustering is enough for the long files you were working with. I have tried it out only on shorter ones but I am curious about the 1.5 hours case you mentioned.
> Thanks,
> Federico

Many thanks @fnlandini. I will test it on my side and let you know the performance on long audios.

**Comment by hxing093020** [comment]
> Hi @SpeechGirl We have just added to the master branch the modifications proposed by @videodanchik If you have time, it would be nice if you can let us know if this faster clustering is enough for the long files you were working with. I have tried it out only on shorter ones but I am curious about the 1.5 hours case you mentioned. Thanks, Federico

I've got pretty good performance and speed on long audios using the up-to-date vbhmm.py.  However, when I tried to do recluster, the gpu runs out of memory for long audios. I think it is because the features of one speaker from the whole audio are too much. Do you have any suggestion to handle this issue?  I paste the error info here:

RuntimeError: CUDA out of memory. Tried to allocate 1.89 GiB (GPU 0; 7.44 GiB total capacity; 4.42 GiB already allocated; 1.86 GiB free; 4.91 GiB reserved in total by PyTorch)

Thanks

**Comment by Sarah-Xing** [comment]
> Hi @SpeechGirl We have just added to the master branch the modifications proposed by @videodanchik If you have time, it would be nice if you can let us know if this faster clustering is enough for the long files you were working with. I have tried it out only on shorter ones but I am curious about the 1.5 hours case you mentioned. Thanks, Federico

Hi @fnlandini,

I've got pretty good performance and speed on long audios using the up-to-date vbhmm.py. However, when I tried to do recluster, the gpu runs out of memory for long audios. I guess it is because the features of one speaker from the whole audio are too much. Do you have any suggestion to handle this issue? I paste the error info here:

RuntimeError: CUDA out of memory. Tried to allocate 1.89 GiB (GPU 0; 7.44 GiB total capacity; 4.42 GiB already allocated; 1.86 GiB free; 4.91 GiB reserved in total by PyTorch)

Thanks

**Comment by fnlandini** [comment]
Hi @SpeechGirl,
Glad to know that it works much faster on very long recordings. I guess what you saw about the memory is expected. Without trying to do anything about how the model performs the operation, an option could be to check if the total amount of speech of a speaker is higher than certain threshold and, if so, calculate two global x-vectors for that speaker with roughly half of the speech each one. Another option I can think of is to check if the [features](https://github.com/BUTSpeechFIT/VBx/blob/7103b76a32dec65239d63fd8047496a71dd0602e/VBx/predict_global_xvectors.py#L197) are more than certain length and if so, reduce them by taking one every two frames. It'll definitely fit in memory and it would correspond to having a longer stride when computing the fbank. I do not know how these options could impact the results but I think they are quick fixes that you could try quickly. If you do, I will be curious about how they perform so feel free to report if they work for you.

**Comment by hxing093020** [comment]
> Hi @SpeechGirl, Glad to know that it works much faster on very long recordings. I guess what you saw about the memory is expected. Without trying to do anything about how the model performs the operation, an option could be to check if the total amount of speech of a speaker is higher than certain threshold and, if so, calculate two global x-vectors for that speaker with roughly half of the speech each one. Another option I can think of is to check if the [features](https://github.com/BUTSpeechFIT/VBx/blob/7103b76a32dec65239d63fd8047496a71dd0602e/VBx/predict_global_xvectors.py#L197) are more than certain length and if so, reduce them by taking one every two frames. It'll definitely fit in memory and it would correspond to having a longer stride when computing the fbank. I do not know how these options could impact the results but I think they are quick fixes that you could try quickly. If you do, I will be curious about how they perform so feel free to report if they work for you.

Thanks for the quick reply. Let me try these suggestions. Will keep you updated.

**Comment by fnlandini** [comment]
Hi @hxing093020 
Do you have any news? Otherwise, I will close this issue.
Thanks

**Comment by hxing093020** [comment]
> Hi @hxing093020 Do you have any news? Otherwise, I will close this issue. Thanks

Thanks to all of you for suggestions on accelerating the diarization process for long audios. We got lots of improvement following these ideas. 

Only one more thing I want to share finally. Other than issues discussed in this thread, like using fastclust, taking xvectors from every two segment, we found that another bottle neck to the processing speed lie in the threshold estimation process for the initial AHC cluster. This process need to go through tens of iterations of computations on large scale vectors, and the code for this part is implemented by Numpy. It is supposed to be much faster if its implemented in pytorch and on GPU. Moreover, if we have an approximate speaker number in advance, use max-speaker as a AHC stop criteria instead of using threshold could bypass this issue and make the whole process way faster.

Hope these observations are helpful for system optimizing in future. You can close this issue. Thanks!

**Comment by videodanchik** [comment]
> > Hi @hxing093020 Do you have any news? Otherwise, I will close this issue. Thanks
> 
> Thanks to all of you for suggestions on accelerating the diarization process for long audios. We got lots of improvement following these ideas.
> 
> Only one more thing I want to share finally. Other than issues discussed in this thread, like using fastclust, taking xvectors from every two segment, we found that another bottle neck to the processing speed lie in the threshold estimation process for the initial AHC cluster. This process need to go through tens of iterations of computations on large scale vectors, and the code for this part is implemented by Numpy. It is supposed to be much faster if its implemented in pytorch and on GPU. Moreover, if we have an approximate speaker number in advance, use max-speaker as a AHC stop criteria instead of using threshold could bypass this issue and make the whole process way faster.
> 
> Hope these observations are helpful for system optimizing in future. You can close this issue. Thanks!

@hxing093020 Good point! Underclustering with the following `VBx` run actually improves performance (at least according to my experience) compared to threshold selection. And additionally, to speed up the performance you can use `numpy.float32` instead `numpy.float64` without significant DER degradation, moreover `Fa`, `Fb` and `PLoop` can be tuned in a way when you can use fever iterations in `VBx` (I manage to make it work with only 2 iterations).

**Comment by Sarah-Xing** [comment]
Thanks, Daniil. It's good to know. I will consider reducing iteration
number if necessary.
