### ISSUE TITLE
what is the difference between plda_psi and plda_tr in line 93 and lines 97 and 98?

### ISSUE THREAD

**Issue by xuanjihe** [BUTSpeechFIT/VBx#35]
![image](https://user-images.githubusercontent.com/28720523/133216096-ba1aaf86-5bac-42c3-99cb-768d8f1e379b.png)
In vbhmm.py, what is the difference between plda_psi and plda_tr in line 93 and lines 97 and 98? I see that some lines in plda_tr are multiplied by -1.

**Comment by fnlandini** [comment]
Hi,
Those lines refer to the transformation applied to the x-vectors explained in [section 2.3](https://reader.elsevier.com/reader/sd/pii/S0885230821000619?token=384630446A906844E3169F7AD77C668F0FF09FB1A83902A33D946966EA218D92303304F4464657DFA730A55384207181&originRegion=eu-west-1&originCreation=20210922085316). Equation 3 (solving the generalized eigenvalue problem) corresponds to line 96. The new value of `plda_tr` is the matrix `E` from the paper (eigenvectors) and `plda_psi` becomes the matrix with the eigenvalues. `W` and `B` are the within and between covariance matrices corresponding to the PLDA model which are passed to eigh for computing eigenvalues and vectors.
If you look at [line 130](https://github.com/BUTSpeechFIT/VBx/blob/87cdad05b8b5f92784634ce11940a4d44288e598/VBx/vbhmm.py#L130), you will see that the transformation to the x-vectors corresponds to the equation 2 in the paper.

If this answers your question, feel free to close this issue.

**Comment by xuanjihe** [comment]
Thank you very much!
