### ISSUE TITLE
AMI DER result  cannot be reproduced

### ISSUE THREAD

**Issue by xiaosujie** [BUTSpeechFIT/VBx#37]
hello, I try to repeat AMI DER result, but when I run AMI_run.sh, I can not get the result which report in the paper "Bayesian HMM clustering of x-vector sequences (VBx)bin speaker diarization: theory, implementation and analysis on standard tasks", can you help me to solve this problem?
I'm also not very clear about the mix-headset and beamformed test，is it only a channel or need some tools to generate it ?

**Comment by MireiaDS** [comment]
Hello,

AMI dataset was recorded using different microphones, including lapel microphones, microphone arrays and headset microphones. Depending on the input audio used for the diarization experiments, the results are different. In the paper we provide results of our system when evaluated on beamformed mic-array audios as well as on Mix-Headset audios.
For the Mix-headset audios, no processing is needed. For the beamformed ones, you need to do beamforming on the microphone array audios. For that we used BeamformIt, with the default configuration for AMI.

All AMI audios can be dowloaded from https://groups.inf.ed.ac.uk/ami/download/.
_AMI documentation_: Carletta, Jean et.al. (2005). The AMI meeting corpus: A pre-announcement. Lecture Notes in Computer Science. 10.1007/11677482_3.

BeamformIt tool: https://github.com/xanguera/BeamformIt. 
_Documentation_: X. Anguera, C. Wooters and J. Hernando, "Acoustic Beamforming for Speaker Diarization of Meetings," in IEEE Transactions on Audio, Speech, and Language Processing, vol. 15, no. 7, pp. 2011-2022, Sept. 2007, doi: 10.1109/TASL.2007.902460.

**Comment by xiaosujie** [comment]
Thanks，now I know the AMI set。
I run the run_example.sh shell , I can get the same result. 
Then I choose one channle from the AMI headset and run the AMI_run.sh shell with default parameters, but I can not reproduced the result in the paper. If I need change the default parameters? Thanks.

**Comment by MireiaDS** [comment]
Did you modify Fb as mentioned in line 6 in AMI_run.sh? 

> Fb=64 # if you want to replicate the results for Mix-Headset, change to Fb=68

**Comment by xiaosujie** [comment]
OK，thanks. I find my script is not the latest, I will download the new and try. Thank you very much.

**Comment by MireiaDS** [comment]
The script was updated recently. 
Please let us know if you manage to reproduce it or if you find other issues.

**Comment by xiaosujie** [comment]
I change Fb=68 on headset dev set，other parameters use default, but the result even get a  little worse. How can I location my problem. Is the xvector wrong or diarization wrong? I have no idea.
headset dev set result as follows:
File               DER    JER    B3-Precision    B3-Recall    B3-F1    GKT(ref, sys)    GKT(sys, ref)    H(ref|sys)    H(sys|ref)    MI    NMI
---------------  -----  -----  --------------  -----------  -------  ---------------  ---------------  ------------  ------------  ----  -----
ES2011a          22.13  59.93            0.62         0.74     0.67             0.64             0.51          1.22          0.63  1.28   0.59
ES2011b          14.55  37.65            0.63         0.77     0.70             0.70             0.56          1.26          0.61  1.61   0.64
ES2011c          25.99  41.97            0.61         0.65     0.63             0.58             0.54          1.33          0.96  1.57   0.58
ES2011d          33.44  61.64            0.56         0.74     0.64             0.65             0.46          1.45          0.63  1.31   0.57
IB4001            7.52  45.50            0.68         0.89     0.77             0.85             0.59          1.11          0.29  1.49   0.69
IB4002            7.04  39.70            0.66         0.86     0.75             0.80             0.58          1.17          0.39  1.62   0.68
IB4003            1.71  22.72            0.73         0.90     0.81             0.84             0.63          0.93          0.28  1.43   0.71
IB4004            2.68  31.06            0.65         0.88     0.75             0.80             0.53          1.14          0.32  1.32   0.66
IB4010            2.54  25.20            0.66         0.86     0.74             0.82             0.59          1.23          0.44  1.78   0.69
IB4011            2.42  21.94            0.71         0.86     0.78             0.82             0.65          1.07          0.42  1.83   0.72
IS1008a           1.38  12.88            0.89         0.94     0.91             0.91             0.84          0.43          0.19  1.82   0.86
IS1008b           1.04   9.20            0.90         0.96     0.93             0.94             0.87          0.40          0.16  2.12   0.88
IS1008c           1.30  12.69            0.83         0.93     0.88             0.91             0.79          0.62          0.24  2.02   0.83
IS1008d           1.60  17.10            0.78         0.90     0.83             0.87             0.73          0.83          0.31  1.98   0.78
TS3004a          14.12  51.31            0.71         0.90     0.79             0.86             0.63          0.97          0.28  1.58   0.73
TS3004b           9.61  29.52            0.67         0.81     0.74             0.76             0.61          1.14          0.52  1.74   0.68
TS3004c           8.65  30.58            0.66         0.81     0.73             0.77             0.60          1.14          0.56  1.75   0.68
TS3004d          51.22  69.87            0.54         0.93     0.68             0.89             0.42          1.45          0.20  1.30   0.64
*** OVERALL ***  10.67  34.47            0.68         0.85     0.76             0.85             0.68          1.09          0.41  5.74   0.89

**Comment by MireiaDS** [comment]
Are you using the lab files we provided  [here](https://github.com/BUTSpeechFIT/AMI-diarization-setup/tree/b158cbecae7c91298346c6bec1d6dcad473f61d3/only_words/labs) as input?

**Comment by xiaosujie** [comment]
Yes, I do. Do you have any other suggestions?

**Comment by MireiaDS** [comment]
You mentioned "I choose one channel from the AMI headset". 
Are you using the **Mix-headset** audios as input? (Not the individual Headsets)

**Comment by xiaosujie** [comment]
How can I get  **Mix-headset**? Just mix four channel together?

**Comment by MireiaDS** [comment]
You simply need to download them from the address pointed out earlier:  https://groups.inf.ed.ac.uk/ami/download/. 
Audio related media streams  -> "Headset mix" wav files

**Comment by xiaosujie** [comment]
ok， I will download the mix-headset audios.
I found it sensitivity to paramter. If I want to reproduce the mix-headset result, are these right parameters?
Fa=0.4
Fb=68
loopP=0.65

**Comment by xiaosujie** [comment]
ok, thanks, I wll try.

**Comment by xiaosujie** [comment]
Hello, I have reproduced the DER result on mix-headset under your help. Thank you very much.
But on the beamformed set, the result is a little different，lower 0.2 point, is it normal here?

**Comment by fnlandini** [comment]
Have you considered this?
`Fb=64 # if you want to replicate the results for Mix-Headset, change to Fb=68`

**Comment by xiaosujie** [comment]
Now, there is no problem. Thank you very much.
