### ISSUE TITLE
Transition matrix update in every iteration

### ISSUE THREAD

**Issue by desh2608** [BUTSpeechFIT/VBx#40]
In the `VB_diarization()` method, it seems that the transition matrix `tr` gets updated in each iteration at line https://github.com/BUTSpeechFIT/VBx/blob/fbc5a1e99ef6146519a3be237f9f72316e64d2ba/VBx/VB_diarization.py#L124 
so the self loop probability keeps increasing? Is this by design?

**Comment by MireiaDS** [comment]
Hi Desh, thanks a lot for pointing that out. It is indeed a bug.

Line 

https://github.com/BUTSpeechFIT/VBx/blob/fbc5a1e99ef6146519a3be237f9f72316e64d2ba/VBx/VB_diarization.py#L97

should be inside the loop as:

    tr = np.eye(minDur*maxSpeakers, k=1)
    tr[minDur-1::minDur,0::minDur]=(1-loopProb)*sp
    tr[(np.arange(1,maxSpeakers+1)*minDur-1,)*2] += loopProb

Nevertheless, the bug only affects the inference when minDur is set to a value higher than 1. In that case the self probability will keep increasing in every iteration.

If minDur is set to 1 (which we always use in our experiments), line 
https://github.com/BUTSpeechFIT/VBx/blob/fbc5a1e99ef6146519a3be237f9f72316e64d2ba/VBx/VB_diarization.py#L123
correctly overwrites all previous values, setting all self transition probabilities to the corresponding speaker priors, and only then they are incremented with the loop probability value.

We will update the code ASAP to solve this issue.

**Comment by fnlandini** [comment]
Hi @desh2608 thanks again for pointing it out. We have verified that we indeed obtain the same results with this modification. The change is in place now. Feel free to reopen the issue if you find any problem.

**Comment by desh2608** [comment]
@MireiaDS @fnlandini no problem, thanks for the quick fix!
