### ISSUE TITLE
Error: Empty input file in predict.py

### ISSUE THREAD

**Issue by Themba4Sho** [BUTSpeechFIT/VBx#47]
Hi there, I am trying to run the example script, I changed to the 8 kHz model and added a file in a new 8kHz folder where I put one example file. When I run the script, I get this error: Empty input file: "example/vad/9BHU18367S.lab". 

I don't get this error when I run the 16 kHz model with the given example file. How do I generate the lab file? My assumption is that if I want to diarise, I just give the input file and model. Thanks.

**Comment by fnlandini** [comment]
Hi, the code in VBx assumes that you have already some voice activity detection (VAD) labels (contents of the .lab files) that mark the segments of speech (everything else is silence). For research purposes, sometimes we have oracle annotations about that (for example, like in the results listed in the README). For a real application, you would need to run VAD on your data. We have a very simple energy-based VAD in another [branch](https://github.com/BUTSpeechFIT/VBx/blob/v1.1_VoxConverse2020/VAD/energy_VAD.py) that you could try to run this. However, I recommend you to use something better like the one from [pyannote](https://huggingface.co/pyannote/voice-activity-detection). I hope this helps.

**Comment by Themba4Sho** [comment]
Hi there, thank you for the response, I will do so.

**Comment by fnlandini** [comment]
I will close the issue now. If you find any trouble, feel free to reopen.
