### ISSUE TITLE
The parameters about overlap in ur paper

### ISSUE THREAD

**Issue by axuan731** [BUTSpeechFIT/VBx#50]
Hello:
       I have read the paper " ANALYSIS OF THE BUT DIARIZATION SYSTEM FOR VOXCONVERSE CHALLENGE", and gain lots of experience. I see the setences that "we tuned the detection threshold on Vox Converse development in order to maximize the precision." I try to use pyannote to detect overlap with default parameters but I dont get a better result than u. Could u share the best parameters for me, it will be helpful for me!! Thanks a lot!

**Comment by fnlandini** [comment]
Hi @axuan731,
I am glad that you found it useful. The threshold parameters from pyannote we used were "offset0.95_onset0.95" if I am not mistaken. However, I am not sure if the pyannote version nowadays is different and perhaps these parameters will not work with the current version as this work was done in 2020. However, I think if you tune the current version, you should be able to obtain better results as the current pyannote model is better.

**Comment by fnlandini** [comment]
Closing the issue for now. Feel free to reopen if you see fit.
