### ISSUE TITLE
Can VBx work on the windows?

### ISSUE THREAD

**Issue by Bagfish** [BUTSpeechFIT/VBx#52]
i am very interested  in this programe when i run the shell file on my windows pc . The warning appear below,i really don't know what it's mean.

**Comment by fnlandini** [comment]
Hi,
The scripts are prepared to run with bash. If you want to run the code with Windows, you will need to adapt the .sh files. Python files should, a priori, work the same.
The warning you see means that you need to set the KALDI_ROOT variable with the path to where you have Kaldi repository. However, how did you reach that warning?
