### ISSUE TITLE
How to load the ResNet model in pytorch

### ISSUE THREAD

**Issue by anuragkumar95** [BUTSpeechFIT/VBx#55]
While it is much easier to work with onnx backend, I would like to run the ResNet embedding model on the GPU using pytorch. There seems to be multiple pytorch checkpoints.. what should be the correct path to the model checkpoint for pytorch load? I see that there are are 5 `.pth` checkpoints and 1 `.onnx` checkpoint.

```
-a----         1/12/2023   1:45 PM       60669003 final.onnx
-a----         1/12/2023   1:45 PM       26214400 raw_81.pth.zip.partaa
-a----         1/12/2023   1:45 PM       26214400 raw_81.pth.zip.partab
-a----         1/12/2023   1:45 PM       26214400 raw_81.pth.zip.partac
-a----         1/12/2023   1:45 PM       26214400 raw_81.pth.zip.partad
-a----         1/12/2023   1:45 PM       21165076 raw_81.pth.zip.partae
```

**Comment by fnlandini** [comment]
Hi Anurag,
The .pth file is split just because it would be too large to be uploaded to the repository. If you look [here](https://github.com/BUTSpeechFIT/VBx/blob/14b512e71619270541813c880963f29bb3d52049/AMI_run.sh#L20) you will see that the model is unzipped like:
```
if [ ! -f $WEIGHTS_DIR/raw_81.pth ]; then
    cat $WEIGHTS_DIR/raw_81.pth.zip.part* > $WEIGHTS_DIR/unsplit_raw_81.pth.zip
        unzip $WEIGHTS_DIR/unsplit_raw_81.pth.zip -d $WEIGHTS_DIR/
fi
```

I hope this helps

**Comment by anuragkumar95** [comment]
Thanks a lot! This helps!
