### ISSUE TITLE
threshold value for AHC 

### ISSUE THREAD

**Issue by somiljain7** [BUTSpeechFIT/VBx#61]
Hi ! 
threshold value of -0.015 was given in example script for AHC clustering .Can you explain this value ? I thought twoGMMcalib_lin() is already calculating the threshold for clustering using cosine similarity matrix scores . 

Thank you

**Comment by Jamiroquai88** [comment]
Hi, this is an experimental value we tuned, I think using 0.0 would give you very similar results in the end.
