### ISSUE TITLE
Derivation of updating formula for $\pi_s$

### ISSUE THREAD

**Issue by alephpi** [BUTSpeechFIT/VBx#63]
Hi I'm reading very carefully on the VBx algorithm based on these two papers:

1. Bayesian HMM clustering of x-vector sequences (VBx) in speaker diarization: Theory, implementation and analysis on standard tasks
2. Bayesian HMM clustering of x-vector sequences (VBx) in speaker diarization: theory, implementation and analysis on standard tasks, technical report

But I cannot deduce what you mentioned as formula (24) in paper (1), which corresponds to https://github.com/BUTSpeechFIT/VBx/blob/57466e6e245d5cdfe2e88ee6503702ace3ffdd03/VBx/VBx.py#L101-L103 in code.

Here is what I developed, we try to maximize ELBO as a function of $\pi_s$, effectively maximizing $\mathbb{E}_{q(Z)}[\ln p(Z)]$, which equals to by (39) in paper (2)

$$
E_{q(\mathbf{Z})}\left[\ln p(\mathbf{Z})\right]=\sum_{s=1}^S\gamma_{1s}\ln\pi_s+\sum_{m=1}^S\sum_{n=1}^S(\sum_{t=2}^T\xi_{tmn})\ln p(n|m)
$$

where $p(n|m)=(1-P_{loop})\pi_n+\delta(m=n)P_{loop}$ by definition. So

$$
E_{q(\mathbf{Z})}\left[\ln p(\mathbf{Z})\right]=\sum_{s=1}^S\gamma_{1s}\ln\pi_s+\sum_{m=1}^S\sum_{n=1}^S(\sum_{t=2}^T\xi_{tmn})\ln [(1-P_{loop})\pi_n+\delta(m=n)P_{loop}]
$$

For a fixed $s$, the terms involved in derivative are just

$$
\gamma_{1s}\ln\pi_s+\sum_{m=1}^S(\sum_{t=2}^T\xi_{tms})\ln [(1-P_{loop})\pi_s+\delta(m=s)P_{loop}]
$$

Split $m=s$ case out of the sum

$$
\gamma_{1s}\ln\pi_s+\sum_{m\neq s}(\sum_{t=2}^T\xi_{tms})\ln [(1-P_{loop})\pi_s]+(\sum_{t=2}^T\xi_{tss})\ln [(1-P_{loop})\pi_s+P_{loop}]
$$

Take derivatives with respect to $\pi_s$ and make it equals to zero

$$
\frac{\gamma_{1s}}{\pi_s}+\sum_{m\neq s}(\sum_{t=2}^T\xi_{tms})\frac{1}{\pi_s}+(\sum_{t=2}^T\xi_{tss})\frac{1-P_{loop}}{(1-P_{loop})\pi_s+P_{loop}}=0
$$

if we denote $P_{loop}/(1-P_{loop})=\alpha$

$$
\frac{\gamma_{1s}}{\pi_s}+\sum_{m\neq s}(\sum_{t=2}^T\xi_{tms})\frac{1}{\pi_s}+(\sum_{t=2}^T\xi_{tss})\frac{1}{\pi_s+\alpha}=0
$$

Solving the equation gives

$$
\pi_s=\alpha\left[\frac{\sum_{t}\xi_{tss}}{\gamma_{1s}+\sum_{m}\sum_{t}\xi_{tms}}-1\right]
$$

where the summation of m runs over all states and t runs from 2 to T (Github renders badly here) and where $\xi_{tmn}=q(z_{t-1}=m,z_t=n)=\frac{A(t-1,m)\bar{p}(\mathbf{x}_t|n)p(n|m)B(t,n)}{\overline{p}(\mathbf{X})}$ by (36) in (2).

**But I don’t see any equivalence between this form and the form given by (24).**

I expect your explanation.

**Comment by MireiaDS** [comment]
Hello, in your derivations, you are mainly missing the Lagrange multipliers that would make sure that the constrain $\sum_{s} \pi_s =1$ holds.

If you inspect the solution you got without using the multipliers, you can see that it suggests that the $\pi_s$ would take negative values, as: 
- $\alpha$ is a positive value
- In the fraction, the numerator is part of the denominator, therefore the fraction has to be <1, and that -1 would result in a negative value.

We included the derivation of such $\pi_s$ values in the technical report, we hope the explanation is complete now, let us know otherwise.

**Comment by alephpi** [comment]
That's very clear. Thank you for your quick and patient complement! I feel very lucky as VBx is my first literature to read as a phd student.

Just a tiny reminder, the constraint $\sum_{s} \pi_s =1$ seems not being correctly rendered in the report.
![截图 2024-02-02 10-52-17](https://github.com/BUTSpeechFIT/VBx/assets/61275421/1d527670-d6ca-490c-912d-1c3b9b8e9504)
