### ISSUE TITLE
Does VBx ever use the training partition in AMI-diarization-setup?

### ISSUE THREAD

**Issue by alephpi** [BUTSpeechFIT/VBx#66]
When consulting https://github.com/BUTSpeechFIT/AMI-diarization-setup.git you proposed, I find it split into dev,test,train and I think dev is development, test is evaluation in your technical report, but what about the train? Have you ever used it in VBx (for xvector extractor training or inference)? I think no. Then what's the purpose of such a partition?

**Comment by alephpi** [comment]
Also I find that the VAD label in `example/vad/ES2005a.lab` is neither same as `AMI-diarization-setup/only_words/labs/train/ES2005a.lab` nor as`AMI-diarization-setup/word_and_vocalsounds/labs/train/ES2005a.lab` Could you explain?
https://github.com/BUTSpeechFIT/VBx/blob/master/example/vad/ES2005a.lab
https://github.com/BUTSpeechFIT/AMI-diarization-setup/blob/b158cbecae7c91298346c6bec1d6dcad473f61d3/only_words/labs/train/ES2005a.lab
https://github.com/BUTSpeechFIT/AMI-diarization-setup/blob/b158cbecae7c91298346c6bec1d6dcad473f61d3/word_and_vocalsounds/labs/train/ES2005a.lab

**Comment by fnlandini** [comment]
Hi,
We have not used the train set in this work. The split follows the Full-corpus-ASR partition of AMI https://groups.inf.ed.ac.uk/ami/corpus/datasets.shtml
This dataset precedes our VBx work and we wanted to be sure that there was consistency in the labels for all parts.

As for `example/vad/ES2005a.lab`, it was probably generated with a system VAD and that is why it does not match the oracle VAD from AMI-diarization-setup. In any case, it is only used as an example to validate that the code runs.

**Comment by alephpi** [comment]
ok I see, thank you!
