### ISSUE TITLE
Technical report link dead

### ISSUE THREAD

**Issue by alephpi** [BUTSpeechFIT/VBx#69]
The technical report link https://www.fit.vutbr.cz/~mireia/CSL_VBHMM_tech_report.pdf mentioned in the paper is dead, so I put a PDF version here just for convenience.
[technical report](https://github.com/user-attachments/files/17041082/Diez.Burget.-.Bayesian.HMM.clustering.of.x-vector.sequences.VBx.pdf)

**Comment by fnlandini** [comment]
Hi @alephpi 
Thanks for pointing it out and sharing the pdf here! I guess they changed something in the paths of BUT. We will try to fix it

**Comment by fnlandini** [comment]
I have uploaded it to https://www.fit.vut.cz/person/landini/public/VBx-techreport.pdf
Unfortunately, the link that we had in the paper will not work but at least it is here are well.
Thank you again for pointing this out. I will close the issue for now.
