### ISSUE TITLE
Sharing the expected output?

### ISSUE THREAD

**Issue by hbredin** [BUTSpeechFIT/VBx#8]
Thanks again for sharing this code.

Any chance you could share the expected output RTTMs for all 4 datasets (and corresponding dev/test splits)?

This would be very useful to check that everything went as expected when running the code.
One can obviously compare the final error rates but having the final RTTMs would make this check even more precise.

**Comment by fnlandini** [comment]
Thanks for the suggestion, Hervé. I have just uploaded them in the folder data.
Please, let us know if you find any troubles.

**Comment by hbredin** [comment]
Great. Thanks!
