### ISSUE TITLE
Clarification about VAD: oracle or automatic?

### ISSUE THREAD

**Issue by hbredin** [BUTSpeechFIT/VBx#9]
I'd like a clarification on the [numbers](https://github.com/BUTSpeechFIT/VBx#results) reported in the paper.
Do you confirm that those are based on oracle VAD?

**Comment by fnlandini** [comment]
Yes, they are all based on oracle VAD. I will add a comment in the README just in case it is not clear.

**Comment by hbredin** [comment]
Awesome. Thanks!
